- hosts: httpd_configuration
  tasks:
    - yum_repository:
        name: docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        description: docker repo
        gpgcheck: no
        enabled: yes
        state: present
    - package:
        name: docker-ce-18.09.1-3.el7.x86_64
        state: present
    - service:
        name: docker
        state: started
        enabled: yes
    - command: pip3 install docker
    - file:
        path: /webserver
        state: directory
    - copy:
        src: /root/home.html
        dest: /webserver
    - docker_image:
        name: httpd
        source: pull
    - docker_container:
        name: Webserver
        image: httpd:latest
        pull: yes
        exposed_ports:
          - "80"
        ports:
          - "80:80"
        volumes:
          - "/webserver:/usr/local/apache2/htdocs"
