- name: Ansible-Docker-Webserver
  hosts: httpd_configuration
  tasks:
    - name: Yum repository for docker
      yum_repository:
        name: docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        description: docker repo
        gpgcheck: no
        enabled: yes
        state: present
    - name: installing docker
      package:
        name: docker-ce-18.09.1-3.el7.x86_64
        state: present
    - name: starting docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: installing docker api  
      command: pip3 install docker
    - name: directory for webserver files
      file:
        path: /webserver
        state: directory
    - name: copying file to webserver
      copy:
        src: /root/home.html
        dest: /webserver
    - name: pulling image of webserver from docker hub
      docker_image:
        name: httpd
        source: pull
    - name: launching docker container 
      docker_container:
        name: Webserver
        image: httpd:latest
        pull: yes
        exposed_ports:
          - "80"
        ports:
          - "80:80"
        volumes:
          - "/webserver:/usr/local/apache2/htdocs"
